package lagatrix.client.gui.components.complex.panels;

import java.text.DecimalFormat;
import lagatrix.client.entities.dto.hardware.CPU;
import lagatrix.client.gui.components.simple.RoundPanel;

/**
 * This components represents an panel who represents the data of CPU.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class CPUPanel extends RoundPanel {
    
    private CPU cpu;

    /**
     * Constructor of the class.
     */
    public CPUPanel() {
        initComponents();
    }

    /**
     * Establish the information of CPU.
     * 
     * @param cpu The CPU object.
     */
    public void setCpu(CPU cpu) {
        this.cpu = cpu;
        putInfo();
    }
    
    /**
     * Set the use of CPU.
     * 
     * @param use His use.
     */
    public void setUse(int use) {
        graphicUse.setPercentaje(use);
    }
    
    /**
     * Set the use of temperature.
     * 
     * @param temp His temperature.
     */
    public void setTemp(int temp) {
        graphicTemp.setPercentaje(temp);
    }

    /**
     * This method put the info of CPU in components.
     */
    private void putInfo() {
        DecimalFormat format = new DecimalFormat("#.##");
        String infoText = "<html>Vel base: %s GHz<br/>Vel turbo: %s GHz<br/>Núcleos: "
                + "%d<br/>Hilos: %d<br/>Caché: %s</html>";
        
        nameLabel.setText(String.format("CPU: %s", cpu.getModel()));
        infoLabel.setText(String.format(infoText, format.format(
                cpu.getMinSpeed()), format.format(cpu.getMaxSpeed()), 
                cpu.getCores(), cpu.getThreads(), cpu.getCacheMemory()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicUse = new lagatrix.client.gui.components.simple.graphics.CircleGraphic();
        graphicTemp = new lagatrix.client.gui.components.simple.graphics.CircleGraphic();
        nameLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        graphicUse.setBackgroundCircleColor(new java.awt.Color(223, 223, 223));
        graphicUse.setDescriptiveMessage("USO");

        javax.swing.GroupLayout graphicUseLayout = new javax.swing.GroupLayout(graphicUse);
        graphicUse.setLayout(graphicUseLayout);
        graphicUseLayout.setHorizontalGroup(
            graphicUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        graphicUseLayout.setVerticalGroup(
            graphicUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        graphicTemp.setBackgroundCircleColor(new java.awt.Color(223, 223, 223));
        graphicTemp.setDescriptiveMessage("TEMP");
        graphicTemp.setUnitPercentaje("ºC");

        javax.swing.GroupLayout graphicTempLayout = new javax.swing.GroupLayout(graphicTemp);
        graphicTemp.setLayout(graphicTempLayout);
        graphicTempLayout.setHorizontalGroup(
            graphicTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        graphicTempLayout.setVerticalGroup(
            graphicTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("CPU Model");

        infoLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(128, 128, 128));
        infoLabel.setText("Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphicUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graphicTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphicTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graphicUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.client.gui.components.simple.graphics.CircleGraphic graphicTemp;
    private lagatrix.client.gui.components.simple.graphics.CircleGraphic graphicUse;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
