package lagatrix.gui.window;

import java.awt.Color;
import javax.swing.JFrame;

/**
 * Represents the window who see the formularys.
 *
 * @author javierfh03
 * @since 0.2
 */
public class WaitWindow extends javax.swing.JDialog {

    /**
     * Constructor of the class.
     *
     * @param father The windows father.
     * @param text The text who display.
     */
    public WaitWindow(JFrame father, String text) {
        super(father, "", true);

        setUndecorated(true);
        initComponents();
        textLabel.setText(text);
        setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new lagatrix.gui.components.simple.RoundPanel();
        loadLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lagatrix");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setBackground(java.awt.Color.darkGray);
        mainPanel.setRadius(61);

        loadLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/load.gif"))); // NOI18N

        textLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        textLabel.setForeground(new java.awt.Color(160, 160, 160));
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLabel.setText("Esperando...");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loadLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(loadLabel)
                .addGap(69, 69, 69)
                .addComponent(textLabel)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*new Thread(() -> {
            for (int i = 0; i < 100000; i++) {
                System.out.println(i);
            }
        }).start();*/
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadLabel;
    private lagatrix.gui.components.simple.RoundPanel mainPanel;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
