package lagatrix.gui.components.complex.fragment;

import java.awt.Graphics;
import java.awt.Point;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import lagatrix.gui.window.MainWindow;
import lagatrix.tools.gui_factory.DrawFactory;

/**
 * This component represents
 * 
 * @author javierfh03
 * @since 0.1
 */
public class Header extends javax.swing.JPanel {
    
    private Window father;
    private Point point;
    private DrawFactory draw;
    private int radius;

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
        dismissButton.setVisible(false);
        draw = new DrawFactory(this);
        radius = 50;
    }
    
    /**
     * If see the dismis button in the header.
     * 
     * @param flag If see.
     */
    public void seeDimiss(boolean flag) {
        dismissButton.setVisible(flag);
        closeButton.setVisible(flag);
    }

    /**
     * Set the frame who contains the header.
     * 
     * @param father The Frame.
     */
    public void setFather(Window father) {
        this.father = father;
        
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point = e.getPoint();
            }
        });
        
        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point currCoords = e.getLocationOnScreen();
                father.setLocation(currCoords.x - point.x, currCoords.y - point.y);
            }
        });
    }

    public void setRadius(int radius) {
        this.radius = radius;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dismissButton = new lagatrix.gui.components.simple.buttons.MiniRoundButton();
        closeButton = new lagatrix.gui.components.simple.buttons.MiniRoundButton();

        setBackground(java.awt.Color.darkGray);

        dismissButton.setBackground(new java.awt.Color(255, 255, 0));
        dismissButton.setDefaultCapable(false);
        dismissButton.setFocusPainted(false);
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(dismissButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        if (father instanceof MainWindow) {
            System.exit(0);
        } else {
            father.dispose();
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
        if (father instanceof JFrame) {
            ((JFrame) father).setState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_dismissButtonActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        draw.roundTop(g, radius);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.buttons.MiniRoundButton closeButton;
    private lagatrix.gui.components.simple.buttons.MiniRoundButton dismissButton;
    // End of variables declaration//GEN-END:variables
}
