package lagatrix.gui.components.complex.fragment;

import java.awt.Graphics;
import lagatrix.gui.components.simple.MenuLabel;
import lagatrix.gui.components.simple.buttons.DefaulRoundButton;
import lagatrix.tools.gui_factory.DrawFactory;

/**
 * Represents the menu of the program.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class Menu extends javax.swing.JPanel {
    
    private MenuLabel selectedLabel;
    private DrawFactory draw;
    private int radius;

    /**
     * Constructor of the class.
     */
    public Menu() {
        initComponents();
        selectLabel(monitoringLabel);
        draw = new DrawFactory(this);
        radius = 50;
    }
    
    public void setRadius(int radius) {
        this.radius = radius;
    }
    
    /**
     * Selects a label.
     * 
     * @param label The label who select.
     */
    public void selectLabel(MenuLabel label) {
        if (selectedLabel != null) {
            selectedLabel.setSelected(false);
        }
        
        label.setSelected(true);
        selectedLabel = label;
    }

    public MenuLabel getSelectedLabel() {
        return selectedLabel;
    }

    public MenuLabel getActionsLabel() {
        return actionsLabel;
    }

    public MenuLabel getApplicationLabel() {
        return applicationLabel;
    }

    public MenuLabel getEventLabel() {
        return eventLabel;
    }

    public DefaulRoundButton getExitButton() {
        return exitButton;
    }

    public MenuLabel getMonitoringLabel() {
        return monitoringLabel;
    }

    public MenuLabel getPartitionLabel() {
        return partitionLabel;
    }

    public MenuLabel getProcessLabel() {
        return processLabel;
    }

    public MenuLabel getUserLabel() {
        return userLabel;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitoringLabel = new lagatrix.gui.components.simple.MenuLabel();
        lagatrixImage = new javax.swing.JLabel();
        actionsLabel = new lagatrix.gui.components.simple.MenuLabel();
        partitionLabel = new lagatrix.gui.components.simple.MenuLabel();
        userLabel = new lagatrix.gui.components.simple.MenuLabel();
        processLabel = new lagatrix.gui.components.simple.MenuLabel();
        eventLabel = new lagatrix.gui.components.simple.MenuLabel();
        applicationLabel = new lagatrix.gui.components.simple.MenuLabel();
        exitButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();

        setBackground(java.awt.Color.darkGray);

        monitoringLabel.setText("Monitorización");
        monitoringLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monitoringLabelMouseClicked(evt);
            }
        });

        lagatrixImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lagatrixImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        actionsLabel.setText("Acciones");
        actionsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionsLabelMouseClicked(evt);
            }
        });

        partitionLabel.setText("Particiones");
        partitionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partitionLabelMouseClicked(evt);
            }
        });

        userLabel.setText("Usuarios");
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        processLabel.setText("Procesos");
        processLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processLabelMouseClicked(evt);
            }
        });

        eventLabel.setText("Eventos");
        eventLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventLabelMouseClicked(evt);
            }
        });

        applicationLabel.setText("Aplicaciones");
        applicationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applicationLabelMouseClicked(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lagatrixImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(monitoringLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(partitionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(processLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applicationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lagatrixImage, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(monitoringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partitionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applicationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void partitionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partitionLabelMouseClicked
        selectLabel(partitionLabel);
    }//GEN-LAST:event_partitionLabelMouseClicked

    private void monitoringLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitoringLabelMouseClicked
        selectLabel(monitoringLabel);
    }//GEN-LAST:event_monitoringLabelMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        selectLabel(userLabel);
    }//GEN-LAST:event_userLabelMouseClicked

    private void eventLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventLabelMouseClicked
        selectLabel(eventLabel);
    }//GEN-LAST:event_eventLabelMouseClicked

    private void processLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processLabelMouseClicked
        selectLabel(processLabel);
    }//GEN-LAST:event_processLabelMouseClicked

    private void applicationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationLabelMouseClicked
        selectLabel(applicationLabel);
    }//GEN-LAST:event_applicationLabelMouseClicked

    private void actionsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionsLabelMouseClicked
        selectLabel(actionsLabel);
    }//GEN-LAST:event_actionsLabelMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        
    }//GEN-LAST:event_exitButtonActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        draw.roundRightBottom(g, radius);
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.MenuLabel actionsLabel;
    private lagatrix.gui.components.simple.MenuLabel applicationLabel;
    private lagatrix.gui.components.simple.MenuLabel eventLabel;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton exitButton;
    private javax.swing.JLabel lagatrixImage;
    private lagatrix.gui.components.simple.MenuLabel monitoringLabel;
    private lagatrix.gui.components.simple.MenuLabel partitionLabel;
    private lagatrix.gui.components.simple.MenuLabel processLabel;
    private lagatrix.gui.components.simple.MenuLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
