package lagatrix.gui.views.main.form;

import lagatrix.exceptions.BadExecutionException;
import lagatrix.exceptions.connection.ConnectionException;
import lagatrix.gui.views.main.getters.Getter;

/**
 * This view make actions in the server
 * 
 * @author javierfh03
 * @since 0.2
 */
public class ActionsView extends MainView {
    
    /**
     * The constructor of the class.
     */
    public ActionsView() {
        initComponents();
    }
    
    @Override
    public Getter inicialiceGetter() {
        return null;  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        rebootButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        powerOffButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();

        setPreferredSize(new java.awt.Dimension(885, 552));

        infoButton.setText("Informe");
        infoButton.setRadius(70);
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        rebootButton.setText("Reiniciar");
        rebootButton.setRadius(70);
        rebootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rebootButtonActionPerformed(evt);
            }
        });

        powerOffButton.setText("Apagar");
        powerOffButton.setRadius(70);
        powerOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerOffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(powerOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(rebootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rebootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        try {
            requester.makeReadRequest(null, "screenfetch");
        } catch (BadExecutionException ex) {
            
        } catch (ConnectionException ex) {
            
        }
    }//GEN-LAST:event_infoButtonActionPerformed

    private void powerOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerOffButtonActionPerformed
        try {
            requester.makeReadRequest(null, "poweroff");
        } catch (BadExecutionException ex) {
            
        } catch (ConnectionException ex) {
            
        }
    }//GEN-LAST:event_powerOffButtonActionPerformed

    private void rebootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rebootButtonActionPerformed
        try {
            requester.makeReadRequest(null, "reboot");
        } catch (BadExecutionException ex) {
            
        } catch (ConnectionException ex) {
            
        }
    }//GEN-LAST:event_rebootButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton infoButton;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton powerOffButton;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton rebootButton;
    // End of variables declaration//GEN-END:variables

}
