package lagatrix.gui.views.main.form;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import lagatrix.entities.actions.ActionsEnum;
import lagatrix.entities.connection.Request;
import lagatrix.entities.dto.event.Event;
import lagatrix.gui.components.complex.containers.RowContainer;
import lagatrix.gui.views.formulary.EventFormularyView;
import lagatrix.gui.views.main.getters.EventGetter;
import lagatrix.gui.views.main.getters.Getter;
import lagatrix.gui.window.FormularyWindow;

/**
 * This view display and manage the events of server.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class EventView extends MainView {

    /**
     * The constructor of the class.
     */
    public EventView() {
        initComponents();
    }
    
    @Override
    public Getter inicialiceGetter() {
        return new EventGetter(this, requester, 5000);
    }

    public RowContainer getRowContainer() {
        return rowContainer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minuteLabel = new javax.swing.JLabel();
        dayMonthLabel = new javax.swing.JLabel();
        weekLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        commandLabel = new javax.swing.JLabel();
        editButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        deleteButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        addButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        jScrollPane = new javax.swing.JScrollPane();
        rowContainer = new lagatrix.gui.components.complex.containers.RowContainer();
        monthLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(885, 552));

        minuteLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        minuteLabel.setForeground(new java.awt.Color(0, 0, 0));
        minuteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minuteLabel.setText("MINUTO");

        dayMonthLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dayMonthLabel.setForeground(new java.awt.Color(0, 0, 0));
        dayMonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayMonthLabel.setText("DÍA MES");

        weekLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        weekLabel.setForeground(new java.awt.Color(0, 0, 0));
        weekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weekLabel.setText("SEMANAL");

        hourLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        hourLabel.setForeground(new java.awt.Color(0, 0, 0));
        hourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourLabel.setText("HORA");

        commandLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        commandLabel.setForeground(new java.awt.Color(0, 0, 0));
        commandLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commandLabel.setText("COMANDO");

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Añadir");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setViewportView(rowContainer);

        monthLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        monthLabel.setForeground(new java.awt.Color(0, 0, 0));
        monthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLabel.setText("MES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(commandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(minuteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(hourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(dayMonthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(weekLabel)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addComponent(jScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minuteLabel)
                    .addComponent(commandLabel)
                    .addComponent(hourLabel)
                    .addComponent(dayMonthLabel)
                    .addComponent(weekLabel)
                    .addComponent(monthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        new FormularyWindow(
                (JFrame) SwingUtilities.getWindowAncestor(this), 
                new EventFormularyView(requester)).setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        EventFormularyView view;
        
        try {
            view = new EventFormularyView(requester, (Event) getRowContainer().getSelectedRow().getEntity());
            
            new FormularyWindow((JFrame) SwingUtilities.getWindowAncestor(this), 
                    view).setVisible(true);
            
            rowContainer.getSelectedRow().setEntity(view.getEntity());
        } catch (NullPointerException ex) {
            System.out.println("No hay ningún evento seleccionado");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Request request = new Request(ActionsEnum.DELETE, Event.class, 
                    ((Event) rowContainer.getSelectedRow().getEntity()));
        
        try {
            requester.makeWriteRequest(this, request, 
                    "No se pusdo eliminar el evento","Borrando evento...");
            
            rowContainer.getSelectedRow().setEntity(null);
        } catch (NullPointerException ex) {
            System.out.println("No hay ningún evento seleccionado");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton addButton;
    private javax.swing.JLabel commandLabel;
    private javax.swing.JLabel dayMonthLabel;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton deleteButton;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton editButton;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel minuteLabel;
    private javax.swing.JLabel monthLabel;
    private lagatrix.gui.components.complex.containers.RowContainer rowContainer;
    private javax.swing.JLabel weekLabel;
    // End of variables declaration//GEN-END:variables

}
