package lagatrix.gui.views.main.form;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import lagatrix.entities.actions.ActionsEnum;
import lagatrix.entities.connection.Request;
import lagatrix.entities.dto.user.User;
import lagatrix.gui.components.complex.containers.RowContainer;
import lagatrix.gui.dialog.ErrorDialog;
import lagatrix.gui.dialog.QuestionDialog;
import lagatrix.gui.views.formulary.UserFormularyView;
import lagatrix.gui.views.main.getters.Getter;
import lagatrix.gui.views.main.getters.UserGetter;
import lagatrix.gui.window.FormularyWindow;

/**
 * This view display and manage the users of server.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class UserView extends MainView {

    /**
     * The constructor of the class.
     */
    public UserView() {
        initComponents();
    }
    
    @Override
    public Getter inicialiceGetter() {
        return new UserGetter(this, requester, 5000);
    }

    public RowContainer getRowContainer() {
        return rowContainer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupLabel = new javax.swing.JLabel();
        shellLabel = new javax.swing.JLabel();
        rootLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        editButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        deleteButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        addButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        jScrollPane = new javax.swing.JScrollPane();
        rowContainer = new lagatrix.gui.components.complex.containers.RowContainer();

        setPreferredSize(new java.awt.Dimension(885, 552));

        groupLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        groupLabel.setForeground(new java.awt.Color(0, 0, 0));
        groupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupLabel.setText("GRUPO");

        shellLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        shellLabel.setForeground(new java.awt.Color(0, 0, 0));
        shellLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shellLabel.setText("SHELL");

        rootLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rootLabel.setForeground(new java.awt.Color(0, 0, 0));
        rootLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rootLabel.setText("ROOT");

        homeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(0, 0, 0));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("HOME");

        userLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("USUARIO");

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Añadir");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setViewportView(rowContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(shellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(rootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addComponent(jScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel)
                    .addComponent(userLabel)
                    .addComponent(homeLabel)
                    .addComponent(shellLabel)
                    .addComponent(rootLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        new FormularyWindow((JFrame) SwingUtilities.getWindowAncestor(this), 
                new UserFormularyView(requester)).setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        UserFormularyView view;
        
        try {
            view = new UserFormularyView(requester, (User) getRowContainer().
                            getSelectedRow().getEntity());
            
            new FormularyWindow((JFrame) SwingUtilities.getWindowAncestor(this), 
                    view).setVisible(true);
            
            rowContainer.getSelectedRow().setEntity(view.getEntity());
        } catch (NullPointerException ex) {
            new ErrorDialog(this, "No hay ningún usuario seleccionado", false).setVisible(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        QuestionDialog question = new QuestionDialog(this, "¿Seguro que quieres borrar el usuario?");
        Request request;
        
        try {
            request = new Request(ActionsEnum.DELETE, User.class, 
                    ((User) rowContainer.getSelectedRow().getEntity()).getUsername());
            
            question.setVisible(true);
            
            if (question.isAccept()) {
                requester.makeWriteRequest(this, request, 
                    "No se pudo borrar al usuario",
                    "Se eliminó el usuario",
                    "Borrando usuario...");
                
                rowContainer.getSelectedRow().setEntity(null);
            }
        } catch (NullPointerException ex) {
           new ErrorDialog(this, "No hay ningún usuario seleccionado", false).setVisible(true);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton addButton;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton deleteButton;
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton editButton;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel rootLabel;
    private lagatrix.gui.components.complex.containers.RowContainer rowContainer;
    private javax.swing.JLabel shellLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

}
