package lagatrix.gui.views.formulary;

import lagatrix.entities.dto.event.Event;

/**
 * This forms represents the manage of events.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class EventFormularyView extends FormularyView {

    private Event event;
    
    /**
     * Constructor of the class.
     */
    public EventFormularyView() {
        initComponents();
    }

    @Override
    public void setEntity(Object entity) {
        event = (Event) entity;
        
        commandInput.setDefaultValue(event.getCommand());
        minuteInput.setDefaultValue(event.getMinute());
        hourInput.setDefaultValue(event.getHour());
        dayMonthInput.setDefaultValue(event.getDayMonth());
        monthInput.setDefaultValue(event.getMonth());
        dayWeekInput.setDefaultValue(event.getDayWeek());
    }
    
    @Override
    public Object obtainEntity() {
        Event newEvent = new Event();
        
        event.setCommand(commandInput.getValue());
        event.setMinute(minuteInput.getValue());
        event.setHour(hourInput.getValue());
        event.setDayMonth(dayMonthInput.getValue());
        event.setMonth(monthInput.getValue());
        event.setDayWeek(dayWeekInput.getValue());
        
        return newEvent;
    }

    @Override
    public Object getEntity() {
        return event;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandInput = new lagatrix.gui.components.simple.input.DefaultInput();
        dayMonthInput = new lagatrix.gui.components.simple.input.DefaultInput();
        dayWeekInput = new lagatrix.gui.components.simple.input.DefaultInput();
        minuteInput = new lagatrix.gui.components.simple.input.DefaultInput();
        monthInput = new lagatrix.gui.components.simple.input.DefaultInput();
        hourInput = new lagatrix.gui.components.simple.input.DefaultInput();

        setBackground(new java.awt.Color(255, 255, 255));

        commandInput.setDefaultValue("");
        commandInput.setDescriptionText("COMANDO");

        dayMonthInput.setDescriptionText("DÍA DEL MES");

        dayWeekInput.setDescriptionText("DÍA DE LA SEMANA");

        minuteInput.setDescriptionText("MINUTO");

        monthInput.setDescriptionText("MES");

        hourInput.setDescriptionText("HORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(commandInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minuteInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(hourInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dayMonthInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(dayWeekInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commandInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minuteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hourInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayWeekInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.input.DefaultInput commandInput;
    private lagatrix.gui.components.simple.input.DefaultInput dayMonthInput;
    private lagatrix.gui.components.simple.input.DefaultInput dayWeekInput;
    private lagatrix.gui.components.simple.input.DefaultInput hourInput;
    private lagatrix.gui.components.simple.input.DefaultInput minuteInput;
    private lagatrix.gui.components.simple.input.DefaultInput monthInput;
    // End of variables declaration//GEN-END:variables

}
