package lagatrix.gui.views.formulary;

import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import lagatrix.connection.RequesterManager;
import lagatrix.entities.actions.ActionsEnum;
import lagatrix.entities.connection.Request;
import lagatrix.entities.dto.event.Event;

/**
 * This forms represents the manage of events.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class EventFormularyView extends FormularyView {

    private Event event;
    private RequesterManager requester;
    
    /**
     * Constructor of the class.
     * 
     * @param requester The requester who use.
     */
    public EventFormularyView(RequesterManager requester) {
        initComponents();
        this.requester = requester;
    }
    
    /**
     * Constructor of the class.
     * 
     * @param event The event who see in form.
     * @param requester The requester who use.
     */
    public EventFormularyView(RequesterManager requester, Event event) {
        this(requester);
        this.event = event;
        
        commandInput.setDefaultValue(event.getCommand());
        minuteInput.setDefaultValue(event.getMinute());
        hourInput.setDefaultValue(event.getHour());
        dayMonthInput.setDefaultValue(event.getDayMonth());
        monthInput.setDefaultValue(event.getMonth());
        dayWeekInput.setDefaultValue(event.getDayWeek());
        
        edit = true;
    }
    
    @Override
    public Object obtainEntity() {
        Event newEvent = new Event();
        
        newEvent.setCommand(commandInput.getValue());
        newEvent.setMinute(minuteInput.getValue());
        newEvent.setHour(hourInput.getValue());
        newEvent.setDayMonth(dayMonthInput.getValue());
        newEvent.setMonth(monthInput.getValue());
        newEvent.setDayWeek(dayWeekInput.getValue());
        
        return newEvent;
    }

    @Override
    public Object getEntity() {
        return event;
    }
    
    @Override
    public void makeAdd() {
        Request request = new Request(ActionsEnum.INSERT, 
                Event.class, obtainEntity());
        
        resoult = requester.makeWriteRequest(((JDialog) SwingUtilities.getWindowAncestor(this))
                .getOwner(), request, "No se pudo añadir el evento", 
                "Se insertó el evento",
                "Insertando el evento...");
    }

    @Override
    public void makeEdit() {
        Event modifyEvent = (Event) obtainEntity();
        Request request = new Request(ActionsEnum.MODIFY, 
                Event.class, event, obtainEntity());
        
        resoult = requester.makeWriteRequest(((JDialog) SwingUtilities.getWindowAncestor(this))
                .getOwner(), request, "No se pudo editar el evento",
                "Se modificó el evento",
                "Editando el evento...");
        
        if (resoult) {
            event = modifyEvent;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandInput = new lagatrix.gui.components.simple.input.DefaultInput();
        dayMonthInput = new lagatrix.gui.components.simple.input.DefaultInput();
        dayWeekInput = new lagatrix.gui.components.simple.input.DefaultInput();
        minuteInput = new lagatrix.gui.components.simple.input.DefaultInput();
        monthInput = new lagatrix.gui.components.simple.input.DefaultInput();
        hourInput = new lagatrix.gui.components.simple.input.DefaultInput();

        commandInput.setDefaultValue("");
        commandInput.setDescriptionText("COMANDO");

        dayMonthInput.setDefaultValue("*");
        dayMonthInput.setDescriptionText("DÍA DEL MES");

        dayWeekInput.setDefaultValue("*");
        dayWeekInput.setDescriptionText("DÍA DE LA SEMANA");

        minuteInput.setDefaultValue("*");
        minuteInput.setDescriptionText("MINUTO");

        monthInput.setDefaultValue("*");
        monthInput.setDescriptionText("MES");

        hourInput.setDefaultValue("*");
        hourInput.setDescriptionText("HORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(commandInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minuteInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(hourInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dayMonthInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(dayWeekInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commandInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minuteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hourInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayWeekInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.input.DefaultInput commandInput;
    private lagatrix.gui.components.simple.input.DefaultInput dayMonthInput;
    private lagatrix.gui.components.simple.input.DefaultInput dayWeekInput;
    private lagatrix.gui.components.simple.input.DefaultInput hourInput;
    private lagatrix.gui.components.simple.input.DefaultInput minuteInput;
    private lagatrix.gui.components.simple.input.DefaultInput monthInput;
    // End of variables declaration//GEN-END:variables

}
