package lagatrix.gui.views.formulary;

import lagatrix.entities.dto.user.User;

/**
 * This forms represents the manage of users.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class UserFormularyView extends FormularyView {

    private User user;
    
    /**
     * Creates new form UserFormularyView
     */
    public UserFormularyView() {
        initComponents();
    }

    @Override
    public void setEntity(Object entity) {
        user = (User) entity;
        
        this.groupInput.setDefaultValue(user.getGroup());
        this.homeInput.setDefaultValue(user.getHome());
        this.shellInput.setDefaultValue(user.getShell());
        this.usernameInput.setDefaultValue(user.getUsername());
    }
    
    @Override
    public Object obtainEntity() {
        User newUser = new User();
        
        newUser.setGroup(groupInput.getValue());
        newUser.setHome(homeInput.getValue());
        newUser.setPassword(passwordInput.getValue());
        newUser.setShell(shellInput.getValue());
        newUser.setUsername(usernameInput.getValue());
        
        return newUser;
    }

    @Override
    public Object getEntity() {
        return user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameInput = new lagatrix.gui.components.simple.input.DefaultInput();
        homeInput = new lagatrix.gui.components.simple.input.DefaultInput();
        shellInput = new lagatrix.gui.components.simple.input.DefaultInput();
        groupInput = new lagatrix.gui.components.simple.input.DefaultInput();
        passwordInput = new lagatrix.gui.components.simple.input.PasswordInput();

        usernameInput.setDefaultValue("");
        usernameInput.setDescriptionText("NOMBRE");

        homeInput.setDescriptionText("HOME");

        shellInput.setDescriptionText("SHELL");

        groupInput.setDescriptionText("GRUPO");

        passwordInput.setDescriptionText("CONTRASEÑA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(shellInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shellInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.input.DefaultInput groupInput;
    private lagatrix.gui.components.simple.input.DefaultInput homeInput;
    private lagatrix.gui.components.simple.input.PasswordInput passwordInput;
    private lagatrix.gui.components.simple.input.DefaultInput shellInput;
    private lagatrix.gui.components.simple.input.DefaultInput usernameInput;
    // End of variables declaration//GEN-END:variables

}
