package lagatrix.gui.components.complex.rows;

import lagatrix.entities.dto.Connection;

/**
 * This class represents the rows who use to represents connections.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class ConnecionRow extends Row {
    
    private Connection connection;

    /**
     * The constructor of the class.
     * 
     * @param connection The connection who see in the row.
     */
    public ConnecionRow(Connection connection) {
        this.connection = connection;
        
        initComponents();
        setRadius(70);
        putInfo();
    }

    @Override
    public void setEntity(Object entity) {
        this.connection = (Connection) entity;
        putInfo();
    }
    
    @Override
    public Object getEntity() {
        return connection;
    }
    
    /**
     * This method put the info of connection in components.
     */
    private void putInfo() {
        distroImage.setIcon(connection.getImage());
        nameLabel.setText(connection.getName());
        ipLabel.setText(connection.getIp().getHostAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipLabel = new javax.swing.JLabel();
        distroImage = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(506, 102));
        setMinimumSize(new java.awt.Dimension(506, 102));
        setPreferredSize(new java.awt.Dimension(506, 102));
        setLayout(null);

        ipLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ipLabel.setForeground(new java.awt.Color(128, 128, 128));
        ipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ipLabel.setText("192.168.122.222");
        add(ipLabel);
        ipLabel.setBounds(353, 10, 135, 82);

        distroImage.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        distroImage.setForeground(new java.awt.Color(128, 128, 128));
        distroImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distroImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distros/default.png"))); // NOI18N
        add(distroImage);
        distroImage.setBounds(18, 10, 130, 82);

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Mi conexión");
        add(nameLabel);
        nameLabel.setBounds(188, 10, 125, 82);
        nameLabel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel distroImage;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
