package lagatrix.gui.components.complex.rows;

import lagatrix.entities.dto.Connection;

/**
 * This class represents the rows who use to represents connections.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class ConnecionRow extends Row {
    
    private Connection connection;

    /**
     * The constructor of the class.
     */
    public ConnecionRow() {
        initComponents();
        setRadius(70);
    }

    @Override
    public void setEntity(Object entity) {
        this.connection = (Connection) entity;
        putInfo();
    }
    
    @Override
    public Object getEntity() {
        return connection;
    }
    
    /**
     * This method put the info of connection in components.
     */
    private void putInfo() {
        distroImage.setIcon(connection.getImage());
        nameLabel.setText(connection.getName());
        ipLabel.setText(connection.getIp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipLabel = new javax.swing.JLabel();
        distroImage = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(506, 102));

        ipLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ipLabel.setForeground(new java.awt.Color(128, 128, 128));
        ipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ipLabel.setText("192.168.122.222");

        distroImage.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        distroImage.setForeground(new java.awt.Color(128, 128, 128));
        distroImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distroImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distros/default.png"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Mi conexión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(distroImage, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ipLabel)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(distroImage, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        nameLabel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel distroImage;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
