package lagatrix.gui.components.complex.rows;

import java.text.DecimalFormat;
import lagatrix.entities.dto.process.UnixProcess;

/**
 * This class represents the rows who use to represents users.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class ProcessRow extends Row {
    
    private UnixProcess process;

    /**
     * The constructor of the class.
     */
    public ProcessRow() {
        initComponents();
    }

    @Override
    public void setEntity(Object entity) {
        this.process = (UnixProcess) entity;
        putInfo();
    }
    
    @Override
    public Object getEntity() {
        return process;
    }
    
    /**
     * This method put the info of event in components.
     */
    private void putInfo() {
        DecimalFormat format = new DecimalFormat("#.##");
        
        establishText(commandText, process.getCommand());
        establishText(usernameText, process.getUsername());
        establishText(pidText, process.getPID() + "");
        establishText(useCPUText, String.format("%s%%", format.format(process.getUseCPU())));
        establishText(useRamText, String.format("%s KB", format.format(process.getUseRAM())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pidText = new javax.swing.JLabel();
        commandText = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        useRamText = new javax.swing.JLabel();
        useCPUText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 70));

        pidText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        pidText.setForeground(new java.awt.Color(128, 128, 128));
        pidText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pidText.setText("0");

        commandText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        commandText.setForeground(new java.awt.Color(128, 128, 128));
        commandText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commandText.setText("Command");

        usernameText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        usernameText.setForeground(new java.awt.Color(128, 128, 128));
        usernameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameText.setText("javier");

        useRamText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        useRamText.setForeground(new java.awt.Color(128, 128, 128));
        useRamText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        useRamText.setText("0 KB");

        useCPUText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        useCPUText.setForeground(new java.awt.Color(128, 128, 128));
        useCPUText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        useCPUText.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(commandText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(pidText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(useCPUText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(useRamText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(pidText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commandText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(useRamText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(useCPUText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commandText;
    private javax.swing.JLabel pidText;
    private javax.swing.JLabel useCPUText;
    private javax.swing.JLabel useRamText;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
