package lagatrix.client.gui.components.complex.fragment;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;

/**
 *
 * @author javier
 */
public class Header extends javax.swing.JPanel {
    
    private JFrame father;
    private Point point;

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
        dismissButton.setVisible(false);
    }
    
    /**
     * If see the dismis button in the header.
     * 
     * @param flag If see.
     */
    public void seeDimiss(boolean flag) {
        dismissButton.setVisible(flag);
    }

    /**
     * Set the frame who contains the header.
     * 
     * @param father The Frame.
     */
    public void setFather(JFrame father) {
        this.father = father;
        
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point = e.getPoint();
            }
        });
        
        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point currCoords = e.getLocationOnScreen();
                father.setLocation(currCoords.x - point.x, currCoords.y - point.y);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dismissButton = new lagatrix.client.gui.components.simple.buttons.MiniRoundButton();
        closeButton = new lagatrix.client.gui.components.simple.buttons.MiniRoundButton();

        setBackground(java.awt.Color.darkGray);

        dismissButton.setBackground(new java.awt.Color(255, 255, 0));
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(dismissButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
        father.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_dismissButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.client.gui.components.simple.buttons.MiniRoundButton closeButton;
    private lagatrix.client.gui.components.simple.buttons.MiniRoundButton dismissButton;
    // End of variables declaration//GEN-END:variables
}
