package lagatrix.gui.components.complex.panels;

import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import lagatrix.entities.dto.hardware.GPU;
import lagatrix.gui.components.simple.RoundPanel;

/**
 * This components represents an panel who represents the data of GPU.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class GPUPanel extends RoundPanel {
    
    private GPU gpu;

    /**
     * Constructor of the class.
     */
    public GPUPanel() {
        initComponents();
    }

    /**
     * Establish the information of GPU.
     * 
     * @param gpu The GPU object.
     */
    public void setGpu(GPU gpu) {
        this.gpu = gpu;
        putInfo();
    }

    /**
     * This method put the info of GPU in components.
     */
    private void putInfo() {
        String imageName = "default";
        String vendor = gpu.getVendor().toLowerCase();
        
        if (Pattern.compile(".*nvidia.*").matcher(vendor).find()) {
            imageName = "nvidia";
        } else if (Pattern.compile(".*amd.*").matcher(vendor).find()) {
            imageName = "amd";
        } else if (Pattern.compile(".*intel.*").matcher(vendor).find()) {
            imageName = "intel";
        } else if (Pattern.compile(".*aspeed.*").matcher(vendor).find()) {
            imageName = "aspeed";
        }
        
        vendorImage.setIcon((Icon) new ImageIcon(getClass().getResource(
                String.format("/gpu/%s.png", imageName))));
        nameLabel.setText(String.format("GPU: %s", gpu.getModel()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        vendorImage = new javax.swing.JLabel();

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("GPU: Modelo desconocido");

        vendorImage.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        vendorImage.setForeground(new java.awt.Color(128, 128, 128));
        vendorImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vendorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gpu/default.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(vendorImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        nameLabel.getAccessibleContext().setAccessibleName("");
        vendorImage.getAccessibleContext().setAccessibleName("");
        vendorImage.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel vendorImage;
    // End of variables declaration//GEN-END:variables
}
