package lagatrix.gui.components.complex.panels;

import lagatrix.entities.dto.os.OSInformation;
import lagatrix.gui.components.simple.RoundPanel;

/**
 * This components represents an panel who represents the data of operative 
 * system.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class OSPanel extends RoundPanel {
    
    private OSInformation os;

    /**
     * Constructor of the class.
     */
    public OSPanel() {
        initComponents();
    }

    /**
     * Establish the information of operative system.
     * 
     * @param os The OSInformation object.
     */
    public void setOs(OSInformation os) {
        this.os = os;
        putInfo();
    }
    
    /**
     * This method put the info of OS in components.
     */
    private void putInfo() {
        nameLabel.setText(os.getDistribution());
        nameLabel.setToolTipText(os.getDistribution());
        
        hostnameLabel.setText(String.format("Hostname: %s", os.getHostname()));
        hostnameLabel.setToolTipText(os.getHostname());
        
        kernelLabel.setText(String.format("Kernel: %s", os.getKernel()));
        kernelLabel.setToolTipText(os.getKernel());
        
        distroImage.setIcon(os.getDistroImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        hostnameLabel = new javax.swing.JLabel();
        distroImage = new javax.swing.JLabel();
        kernelLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(189, 189));
        setLayout(null);

        nameLabel.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Distribución");
        nameLabel.setToolTipText("<none>");
        add(nameLabel);
        nameLabel.setBounds(30, 6, 129, 32);
        nameLabel.getAccessibleContext().setAccessibleName("");

        hostnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        hostnameLabel.setForeground(new java.awt.Color(128, 128, 128));
        hostnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostnameLabel.setText("Hostname");
        hostnameLabel.setToolTipText("<none>");
        add(hostnameLabel);
        hostnameLabel.setBounds(30, 141, 129, 18);

        distroImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(distroImage);
        distroImage.setBounds(30, 44, 129, 85);

        kernelLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        kernelLabel.setForeground(new java.awt.Color(128, 128, 128));
        kernelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kernelLabel.setText("Kernel");
        kernelLabel.setToolTipText("<none>");
        add(kernelLabel);
        kernelLabel.setBounds(30, 166, 129, 18);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel distroImage;
    private javax.swing.JLabel hostnameLabel;
    private javax.swing.JLabel kernelLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
