package lagatrix.gui.components.complex.panels;

import lagatrix.entities.dto.partition.Partition;
import lagatrix.gui.components.simple.RoundPanel;

/**
 * This components represents an panel who represents the data of partition.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class PartitionPanel extends RoundPanel {
    
    private Partition partition;

    /**
     * Constructor of the class.
     */
    public PartitionPanel() {
        initComponents();
    }

    /**
     * Establish the information of partition.
     * 
     * @param partition The Partition object.
     */
    public void setPartition(Partition partition) {
        this.partition = partition;
        putInfo();
    }

    /**
     * This method put the info of partition in components.
     */
    private void putInfo() {
        String infoText = "<html>Tamaño: %s<br/>Usado: %s<br/>Disponible: "
                + "%s<br/>Ruta: %s</html>";
        
        nameLabel.setText(String.format("Particion: %s", partition.getFileSystem()));
        infoLabel.setText(String.format(infoText, partition.getSize(), 
                partition.getUsedStorage(), partition.getAvatible(), partition.getMountPath()));
        graphicUse.setPercentaje(partition.getPercernage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicUse = new lagatrix.gui.components.simple.graphics.CircleGraphic();
        nameLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        graphicUse.setBackgroundCircleColor(new java.awt.Color(223, 223, 223));
        graphicUse.setDescriptiveMessage("USO");

        javax.swing.GroupLayout graphicUseLayout = new javax.swing.GroupLayout(graphicUse);
        graphicUse.setLayout(graphicUseLayout);
        graphicUseLayout.setHorizontalGroup(
            graphicUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        graphicUseLayout.setVerticalGroup(
            graphicUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Particion");

        infoLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(128, 128, 128));
        infoLabel.setText("Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(graphicUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphicUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.graphics.CircleGraphic graphicUse;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
