package lagatrix.gui.components.complex.panels;

import lagatrix.entities.dto.hardware.RAM;
import lagatrix.gui.components.simple.RoundPanel;

/**
 * This components represents an panel who represents the data of RAM.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class RAMPanel extends RoundPanel {
    
    private RAM ram;

    /**
     * Constructor of the class.
     */
    public RAMPanel() {
        initComponents();
    }

    /**
     * Establish the information of RAM.
     * 
     * @param ram The RAM object.
     */
    public void setRam(RAM ram) {
        this.ram = ram;
        putInfo();
    }
    
    /**
     * Set the use of RAM.
     * 
     * @param use His use.
     */
    public void setUse(int use) {
        graphicUse.setPercentaje(use);
    }
    
    /**
     * This method put the info of RAM in components.
     */
    private void putInfo() {
        totalRam.setText(String.format("Total %s%s", ram.getCapacity(), 
                ram.getUnitCapacity()));
        graphicUse.setTotalMemory(ram.getCapacity());
        graphicUse.setUnitMemory(ram.getUnitCapacity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicUse = new lagatrix.gui.components.simple.graphics.CircleGraphicRAM();
        nameLabel = new javax.swing.JLabel();
        totalRam = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(189, 189));

        graphicUse.setMinimumSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout graphicUseLayout = new javax.swing.GroupLayout(graphicUse);
        graphicUse.setLayout(graphicUseLayout);
        graphicUseLayout.setHorizontalGroup(
            graphicUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        graphicUseLayout.setVerticalGroup(
            graphicUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(128, 128, 128));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("RAM");

        totalRam.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        totalRam.setForeground(new java.awt.Color(128, 128, 128));
        totalRam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalRam.setText("Total: 0GB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalRam, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(graphicUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphicUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRam, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        nameLabel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.graphics.CircleGraphicRAM graphicUse;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel totalRam;
    // End of variables declaration//GEN-END:variables
}
