package lagatrix.gui.components.complex.panels;

import lagatrix.gui.components.simple.RoundPanel;

/**
 * This components represents an panel who wait an action.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class WaitApplicationPanel extends RoundPanel {

    /**
     * Constructor of the class.
     */
    public WaitApplicationPanel() {
        initComponents();
    }

    /**
     * Set the text who display.
     * 
     * @param text The text who display.
     */
    public void setText(String text) {
        this.textLabel.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.darkGray);

        loadLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/load.gif"))); // NOI18N

        textLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        textLabel.setForeground(new java.awt.Color(160, 160, 160));
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLabel.setText("Esperando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loadLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(loadLabel)
                .addGap(69, 69, 69)
                .addComponent(textLabel)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadLabel;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
