package lagatrix.gui.dialog.status;

import java.awt.Color;
import java.awt.Window;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import lagatrix.tools.gui_factory.AjustTextFactory;

/**
 * This dialog see if an correct action ocurred.
 * 
 * @author javierfh03
 * @since 0.3
 */
public class CorrectDialog extends javax.swing.JDialog {

    /**
     * Constructor of the class.
     * 
     * @param father The window father.
     * @param message The messge who see.
     */
    public CorrectDialog(Window father, String message) {
        super(father, "");
        setModal(true);
        
        setUndecorated(true);
        initComponents();
        textLabel.setText(AjustTextFactory.ajust(message));
        setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
    }
    
    /**
     * Constructor of the class.
     * 
     * @param father The panel father.
     * @param message The messge who see.
     */
    public CorrectDialog(JPanel father, String message) {
        this(SwingUtilities.getWindowAncestor(father), message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new lagatrix.gui.components.simple.RoundPanel();
        actionButton = new lagatrix.gui.components.simple.buttons.DefaulRoundButton();
        header = new lagatrix.gui.components.complex.fragment.Header();
        imageLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lagatrix");

        mainPanel.setBackground(new java.awt.Color(235, 235, 235));
        mainPanel.setRadius(61);

        actionButton.setText("Aceptar");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        header.setFather(this);

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/status/correct.png"))); // NOI18N

        textLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textLabel.setForeground(java.awt.Color.darkGray);
        textLabel.setText("Texto correcto ejemplo");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(imageLabel)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        dispose();
    }//GEN-LAST:event_actionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.gui.components.simple.buttons.DefaulRoundButton actionButton;
    private lagatrix.gui.components.complex.fragment.Header header;
    private javax.swing.JLabel imageLabel;
    private lagatrix.gui.components.simple.RoundPanel mainPanel;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
