package lagatrix.client.gui.components.complex.rows;

import lagatrix.client.entities.dto.event.Event;
import lagatrix.client.gui.components.simple.BoleanCircle;

/**
 * This class represents the rows who use to represents events.
 * 
 * @author javierfh03
 * @since 0.1
 */
public class EventRow extends Row {
    
    private Event event;

    /**
     * Creates new form EventRow
     */
    public EventRow() {
        initComponents();
    }

    @Override
    public void setEntity(Object entity) {
        this.event = (Event) entity;
        putInfo();
    }
    
    @Override
    public Object getEntity() {
        return event;
    }
    
    /**
     * This method put the info of event in components.
     */
    private void putInfo() {
        commandText.setText(event.getCommand());
        commandText.setToolTipText(event.getCommand());
        
        establishCircle(hourCircle, event.getHour());
        establishCircle(minuteCircle, event.getMinute());
        establishCircle(dayCircle, event.getDayMonth());
        establishCircle(monthCircle, event.getMonth());
        establishCircle(weekCircle, event.getDayWeek());
    }
    
    /**
     * Sets info of event into the circle.
     * 
     * @param circle The circle.
     * @param time Teh information of time of event.
     */
    private static void establishCircle(BoleanCircle circle, String time) {
        circle.setStatus(!time.equals("*"));
        circle.setToolTipText(time);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandText = new javax.swing.JLabel();
        hourCircle = new lagatrix.client.gui.components.simple.BoleanCircle();
        minuteCircle = new lagatrix.client.gui.components.simple.BoleanCircle();
        dayCircle = new lagatrix.client.gui.components.simple.BoleanCircle();
        monthCircle = new lagatrix.client.gui.components.simple.BoleanCircle();
        weekCircle = new lagatrix.client.gui.components.simple.BoleanCircle();

        commandText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        commandText.setForeground(new java.awt.Color(128, 128, 128));
        commandText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commandText.setText("Command");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(commandText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(hourCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(minuteCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(dayCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(monthCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(weekCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weekCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dayCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minuteCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hourCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commandText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commandText;
    private lagatrix.client.gui.components.simple.BoleanCircle dayCircle;
    private lagatrix.client.gui.components.simple.BoleanCircle hourCircle;
    private lagatrix.client.gui.components.simple.BoleanCircle minuteCircle;
    private lagatrix.client.gui.components.simple.BoleanCircle monthCircle;
    private lagatrix.client.gui.components.simple.BoleanCircle weekCircle;
    // End of variables declaration//GEN-END:variables
}
