package lagatrix.client.gui.views.main.form;

import lagatrix.client.connection.RequesterManager;
import lagatrix.client.gui.components.complex.containers.PanelContainer;
import lagatrix.client.gui.views.main.getters.Getter;

/**
 * This view display the applications of server and manage it.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class AplicationView extends MainView {
    
    private RequesterManager requester;

    /**
     * The constructor of the class.
     */
    public AplicationView() {
        initComponents();
        mariaDBApplicationPanel.isApplicationInstaled(true);
    }
    
    @Override
    public Getter inicialiceGetter() {
        throw new UnsupportedOperationException();
    }

    public PanelContainer getPanelContainer() {
        return panelContainer1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new lagatrix.client.gui.components.simple.buttons.DefaulRoundButton();
        upgradeButton = new lagatrix.client.gui.components.simple.buttons.DefaulRoundButton();
        jScrollPane = new javax.swing.JScrollPane();
        panelContainer1 = new lagatrix.client.gui.components.complex.containers.PanelContainer();
        pythonApplicationPanel = new lagatrix.client.gui.components.complex.panels.ApplicationPanel();
        phpApplicationPanel = new lagatrix.client.gui.components.complex.panels.ApplicationPanel();
        mariaDBApplicationPanel = new lagatrix.client.gui.components.complex.panels.ApplicationPanel();
        apacheApplicationPanel = new lagatrix.client.gui.components.complex.panels.ApplicationPanel();
        bindApplicationPanel = new lagatrix.client.gui.components.complex.panels.ApplicationPanel();
        vsftpdApplicationPanel = new lagatrix.client.gui.components.complex.panels.ApplicationPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(885, 552));

        updateButton.setText("Actualizar sistema");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        upgradeButton.setText("Actualizar repositorios");
        upgradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgradeButtonActionPerformed(evt);
            }
        });

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pythonApplicationPanel.setAptName("python3");
        pythonApplicationPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/python.png"))); // NOI18N
        pythonApplicationPanel.setPacmanName("python3");
        pythonApplicationPanel.setTitleLabel("Python");
        pythonApplicationPanel.setYumName("python3");
        pythonApplicationPanel.setZypperName("python3");
        panelContainer1.add(pythonApplicationPanel);

        phpApplicationPanel.setAptName("php");
        phpApplicationPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/php.png"))); // NOI18N
        phpApplicationPanel.setName("php"); // NOI18N
        phpApplicationPanel.setPacmanName("php");
        phpApplicationPanel.setTitleLabel("PHP");
        phpApplicationPanel.setYumName("php");
        phpApplicationPanel.setZypperName("php");
        panelContainer1.add(phpApplicationPanel);

        mariaDBApplicationPanel.setAptName("mariadb-server");
        mariaDBApplicationPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/mariadb.png"))); // NOI18N
        mariaDBApplicationPanel.setPacmanName("mariadb");
        mariaDBApplicationPanel.setTitleLabel("MariaDB");
        mariaDBApplicationPanel.setYumName("mariadb-server");
        mariaDBApplicationPanel.setZypperName("mariadb-server");
        panelContainer1.add(mariaDBApplicationPanel);

        apacheApplicationPanel.setAptName("apache2");
        apacheApplicationPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/apache2.png"))); // NOI18N
        apacheApplicationPanel.setPacmanName("apache");
        apacheApplicationPanel.setTitleLabel("Apache 2");
        apacheApplicationPanel.setYumName("httpd");
        apacheApplicationPanel.setZypperName("httpd");
        panelContainer1.add(apacheApplicationPanel);

        bindApplicationPanel.setAptName("bind9");
        bindApplicationPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/bind9.png"))); // NOI18N
        bindApplicationPanel.setPacmanName("bind");
        bindApplicationPanel.setTitleLabel("Bind9");
        bindApplicationPanel.setYumName("bind");
        bindApplicationPanel.setZypperName("bind");
        panelContainer1.add(bindApplicationPanel);

        vsftpdApplicationPanel.setAptName("vsftpd");
        vsftpdApplicationPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/vsftpd.png"))); // NOI18N
        vsftpdApplicationPanel.setPacmanName("vsftpd");
        vsftpdApplicationPanel.setTitleLabel("VSFTP");
        vsftpdApplicationPanel.setYumName("vsftpd");
        vsftpdApplicationPanel.setZypperName("vsftpd");
        panelContainer1.add(vsftpdApplicationPanel);

        jScrollPane.setViewportView(panelContainer1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(upgradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upgradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 98, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void upgradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgradeButtonActionPerformed
        
    }//GEN-LAST:event_upgradeButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.client.gui.components.complex.panels.ApplicationPanel apacheApplicationPanel;
    private lagatrix.client.gui.components.complex.panels.ApplicationPanel bindApplicationPanel;
    private javax.swing.JScrollPane jScrollPane;
    private lagatrix.client.gui.components.complex.panels.ApplicationPanel mariaDBApplicationPanel;
    private lagatrix.client.gui.components.complex.containers.PanelContainer panelContainer1;
    private lagatrix.client.gui.components.complex.panels.ApplicationPanel phpApplicationPanel;
    private lagatrix.client.gui.components.complex.panels.ApplicationPanel pythonApplicationPanel;
    private lagatrix.client.gui.components.simple.buttons.DefaulRoundButton updateButton;
    private lagatrix.client.gui.components.simple.buttons.DefaulRoundButton upgradeButton;
    private lagatrix.client.gui.components.complex.panels.ApplicationPanel vsftpdApplicationPanel;
    // End of variables declaration//GEN-END:variables

}
