package lagatrix.client.gui.views.main.form;

import lagatrix.client.connection.RequesterManager;
import lagatrix.client.entities.actions.ActionsEnum;
import lagatrix.client.entities.dto.event.Event;
import lagatrix.client.entities.dto.user.User;
import lagatrix.client.exceptions.BadExecutionException;
import lagatrix.client.exceptions.connection.ConnectionException;
import lagatrix.client.gui.components.complex.containers.RowContainer;
import lagatrix.client.gui.components.complex.rows.EventRow;
import lagatrix.client.gui.components.complex.rows.UserRow;
import lagatrix.client.gui.views.main.getters.EventGetter;
import lagatrix.client.gui.views.main.getters.Getter;
import lagatrix.client.gui.views.main.getters.UserGetter;

/**
 * This view display and manage the events of server.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class EventView extends MainView {
    
    private RequesterManager requester;

    /**
     * The constructor of the class.
     */
    public EventView() {
        initComponents();
    }
    
    @Override
    public Getter inicialiceGetter() {
        return new EventGetter(this, requester, 100000);
    }

    public RowContainer getRowContainer() {
        return rowContainer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupLabel = new javax.swing.JLabel();
        shellLabel = new javax.swing.JLabel();
        rootLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        editButton = new lagatrix.client.gui.components.simple.buttons.DefaulRoundButton();
        deleteButton = new lagatrix.client.gui.components.simple.buttons.DefaulRoundButton();
        addButton = new lagatrix.client.gui.components.simple.buttons.DefaulRoundButton();
        jScrollPane = new javax.swing.JScrollPane();
        rowContainer = new lagatrix.client.gui.components.complex.containers.RowContainer();
        rootLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(885, 552));

        groupLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        groupLabel.setForeground(new java.awt.Color(0, 0, 0));
        groupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupLabel.setText("MINUTO");

        shellLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        shellLabel.setForeground(new java.awt.Color(0, 0, 0));
        shellLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shellLabel.setText("DÍA MES");

        rootLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rootLabel.setForeground(new java.awt.Color(0, 0, 0));
        rootLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rootLabel.setText("SEMANAL");

        homeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(0, 0, 0));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("HORA");

        userLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("COMANDO");

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Añadir");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setViewportView(rowContainer);

        rootLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rootLabel1.setForeground(new java.awt.Color(0, 0, 0));
        rootLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rootLabel1.setText("MES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(shellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(rootLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(rootLabel)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addComponent(jScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel)
                    .addComponent(userLabel)
                    .addComponent(homeLabel)
                    .addComponent(shellLabel)
                    .addComponent(rootLabel)
                    .addComponent(rootLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        rowContainer.addRow(new EventRow());
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            requester.makeRequest(ActionsEnum.DELETE, User.class, 
                    ((Event) rowContainer.getSelectedRow().getEntity()).getCommand());
        } catch (BadExecutionException ex) {
            
        } catch (ConnectionException ex) {
            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.client.gui.components.simple.buttons.DefaulRoundButton addButton;
    private lagatrix.client.gui.components.simple.buttons.DefaulRoundButton deleteButton;
    private lagatrix.client.gui.components.simple.buttons.DefaulRoundButton editButton;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel rootLabel;
    private javax.swing.JLabel rootLabel1;
    private lagatrix.client.gui.components.complex.containers.RowContainer rowContainer;
    private javax.swing.JLabel shellLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

}
