package lagatrix.client.gui.views.main.form;

import lagatrix.client.connection.RequesterManager;
import lagatrix.client.gui.components.complex.containers.PanelContainer;
import lagatrix.client.gui.views.main.getters.Getter;
import lagatrix.client.gui.views.main.getters.PartitionGetter;

/**
 * This view display the partitions of server.
 * 
 * @author javierfh03
 * @since 0.2
 */
public class PartitionView extends MainView {
    
    private RequesterManager requester;

    /**
     * The constructor of the class.
     */
    public PartitionView() {
        initComponents();
    }
    
    @Override
    public Getter inicialiceGetter() {
        return new PartitionGetter(this, requester, 10000);
    }

    public PanelContainer getPanelContainer() {
        return panelContainer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerBase = new lagatrix.client.gui.components.complex.containers.ContainerBase();
        panelContainer = new lagatrix.client.gui.components.complex.containers.PanelContainer();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(885, 552));

        javax.swing.GroupLayout containerBaseLayout = new javax.swing.GroupLayout(containerBase);
        containerBase.setLayout(containerBaseLayout);
        containerBaseLayout.setHorizontalGroup(
            containerBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerBaseLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        containerBaseLayout.setVerticalGroup(
            containerBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerBaseLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lagatrix.client.gui.components.complex.containers.ContainerBase containerBase;
    private lagatrix.client.gui.components.complex.containers.PanelContainer panelContainer;
    // End of variables declaration//GEN-END:variables

}
